/* © Copyright CERN 2022. All rights reserved. This software is released under a CERN proprietary software license.
 * Any permission to use it shall be granted in writing. Requests shall be addressed to CERN through mail-KT@cern.ch
 *
 * Author: Natalija Topalovic CERN BE/CEM/MRO 2022
 *
 *  ==================================================================================================
 */

#pragma once

#include <cstdint>
#include <map>
#include <string>

namespace crf::devices::canopendrivers {

/**
 * @ingroup group_cia_four_zero_two
 * @brief Enum class that defines all the 6000s registers which are related to reading/setting position,
 * velocity, tourque, modes of operation etc.
 * (These registers are specific for the 402 profile (aka profile for drivers))
 */
struct CiA402Registers {
    enum Type : uint16_t {
        AbortConnection = 0x6007,
        ErrorCode = 0x603F,
        ControlWord = 0x6040,
        StatusWord = 0x6041,
        VLTargetVelocity = 0x6042,
        VLVelocityDemand = 0x6043,
        VLVelocityActualValue = 0x6044,
        VelocityMinMaxAmount = 0x6046,
        VLVelocityAcceleration = 0x6048,
        VLVelocityDeceleration = 0x6049,
        VLVelocityQuickStop = 0x604A,
        VLSetPointFactor = 0x604B,
        VLDimensionFactor = 0x604C,
        QuickStopOptionCode = 0x605A,
        ShutdownOptionCode = 0x605B,
        DisableOperationOptionCode = 0x605C,
        HaltOptionCode = 0x605D,
        FaultReactionOptionCode = 0x605E,
        ModesOfOperation = 0x6060,
        ModesOfOperationDisplay = 0x6061,
        PositionDemandValue = 0x6062,
        PositionActualInternalValue = 0x6063,
        PositionActualValue = 0x6064,
        FollowingErrorWindow = 0x6065,
        FollowingErrorTimeout = 0x6066,
        PositionWindow = 0x6067,
        PositionWindowTime = 0x6068,
        VelocitySensorActualValue = 0x6069,
        SensorSelectionCode = 0x606A,
        VelocityDemandValue = 0x606B,
        VelocityActualValue = 0x606C,
        VelocityWindow = 0x606D,
        VelocityWindowTime = 0x606E,
        VelocityThreshold = 0x606F,
        VelocityThresholdTime = 0x6070,
        TargetTorque = 0x6071,
        MaxTorque = 0x6072,
        MaxCurrent = 0x6073,
        TorqueDemandValue = 0x6074,
        MotorRatedCurrent = 0x6075,
        MotorRatedTorque = 0x6076,
        TorqueActualValue = 0x6077,
        CurrentActualValue = 0x6078,
        DCLinkCircuitVoltage = 0x6079,
        TargetPosition = 0x607A,
        PositionRangeLimit = 0x607B,
        HomeOffset = 0x607C,
        SoftwarePositionLimit = 0x607D,
        Polarity = 0x607E,
        MaxProfileVelocity = 0x607F,
        MaxMotorSpeed = 0x6080,
        ProfileVelocity = 0x6081,
        EndVelocity = 0x6082,
        ProfileAcceleration = 0x6083,
        ProfileDeceleration = 0x6084,
        QuickStopDeceleration = 0x6085,
        MotionProfileType = 0x6086,
        TorqueSlope = 0x6087,
        TorqueProfileType = 0x6088,
        PositionEncoderResolution = 0x608F,
        VelocityEncoderResolution = 0x6090,
        GearRatio = 0x6091,
        FeedConstant = 0x6092,
        VelocityFactor = 0x6096,
        AccelerationFactor = 0x6097,
        HomingMethod = 0x6098,
        HomingSpeeds = 0x6099,
        HomingAcceleration = 0x609A,
        JerkFactor = 0x60A2,
        ProfileJerkUse = 0x60A3,
        ProfileJerk = 0x60A4,
        SIUnitPosition = 0x60A8,
        SIUnitVelocity = 0x60A9,
        SIUnitAcceleration = 0x60AA,
        SIUnitJerk = 0x60AB,
        PositionOffset = 0X60B0,
        VelocityOffset = 0x60B1,
        TorqueOffset = 0x60B2,
        AdditionalHomeOffset = 0x60B3,
        TouchProbeFunction = 0x60B8,
        TouchProbeStatus = 0x60B9,
        TouchProbe1PositionPositiveEdge = 0x60BA,
        TouchProbe1PositionNegativeEdge = 0x60BB,
        TouchProbe2PositionPositiveEdge = 0x60BC,
        TouchProbe2PositionNegativeEdge = 0x60BD,
        InterpolationSubModeSelect = 0x60C0,
        InterpolationDataRecord = 0x60C1,
        InterpolationTimePeriod = 0x60C2,
        InterpolationDataConfiguration = 0x60C4,
        MaxAcceleration = 0x60C5,
        MaxDeceleration = 0x60C6,
        LowVelocityLimitValue = 0x60C8,
        HighVelocityLimitValue = 0x60C9,
        TorqueLimitationOptionCode = 0x60CA,
        AccelerationActualValue = 0x60CB,
        TorqueLimitationStatus = 0x60CC,
        TouchProbeSource = 0x60D0,
        TouchProbeTimeStamp1PositiveValue = 0x60D1,
        TouchProbeTimeStamp1NegativeValue = 0x60D2,
        TouchProbeTimeStamp2PositiveValue = 0x60D3,
        TouchProbeTimeStamp2NegativeValue = 0x60D4,
        TouchProbeTimeStamp1PositiveEdgeCounter = 0x60D5,
        TouchProbeTimeStamp1NegativeEdgeCounter = 0x60D6,
        TouchProbeTimeStamp2PositiveEdgeCounter = 0x60D7,
        TouchProbeTimeStamp2NegativeEdgeCounter = 0x60D8,
        PositiveTorqueLimitValue = 0x60E0,
        NegativeTorqueLimitValue = 0x60E1,
        SupportedHomingMethods = 0x60E3,
        AdditionalPositionActualValue = 0x60E4,
        AdditionalVelocityActualValue = 0x60E5,
        AdditionalPositionEncoderResolutionEncoderIncrements = 0x60E6,
        AdditionalVelocityEncoderResolutionEncoderIncPerSec = 0x60E7,
        AdditionalGearRatioMotorShaftRevolutions = 0x60E8,
        AdditionalFeedConstantFeed = 0x60E9,
        CommutationAngle = 0x60EA,
        AdditionalPositionEncoderResolutionMotorRevolutions = 0x60EB,
        AdditionalVelocityEncoderResolutionMotorRevPerSec = 0x60EC,
        AdditionalGearRatioDrivingrShaftRevolutions = 0x60ED,
        AdditionalFeedDrivingrShaftRevolutions = 0x60EE,
        AdditionalSensorSelection = 0x60EF,
        EncoderInversion = 0x60F0,
        AdditionalEncoderInversion = 0x60F1,
        PositioningOptionCode = 0x60F2,
        FollowingErrorActualValue = 0x60F4,
        MaxSlippage = 0x60F8,
        ControlEffort = 0x60FA,
        PositionDemandInternalValue = 0x60FC,
        DigitalInputs = 0x60FD,
        DigitalOutputs = 0x60FE,
        TargetVelocity = 0x60FF,
        PositionActualValue64Bit = 0x6112,
        AdditionalPositionActualValue64Bit = 0x6131,
        CAMStateRegister = 0x6180,
        CAMEnableRegister = 0x6181,
        CAMPolarityRegister = 0x6182,
        CAMPositionSelectionRegister = 0x6183,
        CAM1LowLimit = 0x6191,
        CAM2LowLimit = 0x6192,
        CAM3LowLimit = 0x6193,
        CAM4LowLimit = 0x6194,
        CAM1HighLimit = 0x61A1,
        CAM2HighLimit = 0x61A2,
        CAM3HighLimit = 0x61A3,
        CAM4HighLimit = 0x61A4,
        CAM1Hysteresis = 0x61B1,
        CAM2Hysteresis = 0x61B2,
        CAM3Hysteresis = 0x61B3,
        CAM4Hysteresis = 0x61B4,
        CAM1PositionSourceSelection = 0x61C1,
        CAM2PositionSourceSelection = 0x61C2,
        CAM3PositionSourceSelection = 0x61C3,
        CAM4PositionSourceSelection = 0x61C4,
        CAM1Duration = 0x61D1,
        CAM2Duration = 0x61D2,
        CAM3Duration = 0x61D3,
        CAM4Duration = 0x61D4,
        CAM1SwitchPointConfiguration = 0x61E1,
        CAM2SwitchPointConfiguration = 0x61E2,
        CAM3SwitchPointConfiguration = 0x61E3,
        CAM4SwitchPointConfiguration = 0x61E4,
        MotorType = 0x6402,
        MotorCatalogueNumber = 0x6403,
        MotorManufacturer = 0x6404,
        HttpMotorCatalogueAddress = 0x6405,
        MotorCalibrationDate = 0x6406,
        MotorServicePeriod = 0x6407,
        SupportedDriveModes = 0x6502,
        DriveCatalogueNumber = 0x6503,
        HttpDriveCatalogueAddress = 0x6505,
        VersionNumber = 0x67FE
    };
};

using CiA402 = CiA402Registers::Type;

const std::map<CiA402, std::string> CiA402toString = {
    {CiA402::AbortConnection, "AbortConnection"},
    {CiA402::ErrorCode, "ErrorCode"},
    {CiA402::ControlWord, "ControlWord"},
    {CiA402::StatusWord, "StatusWord"},
    {CiA402::VLTargetVelocity, "VLTargetVelocity"},
    {CiA402::VLVelocityDemand, "VLVelocityDemand"},
    {CiA402::VLVelocityActualValue, "VLVelocityActualValue"},
    {CiA402::VelocityMinMaxAmount, "VelocityMinMaxAmount"},
    {CiA402::VLVelocityAcceleration, "VLVelocityAcceleration"},
    {CiA402::VLVelocityDeceleration, "VLVelocityDeceleration"},
    {CiA402::VLVelocityQuickStop, "VLVelocityQuickStop"},
    {CiA402::VLSetPointFactor, "VLSetPointFactor"},
    {CiA402::VLDimensionFactor, "VLDimensionFactor"},
    {CiA402::QuickStopOptionCode, "QuickStopOptionCode"},
    {CiA402::ShutdownOptionCode, "ShutdownOptionCode"},
    {CiA402::DisableOperationOptionCode, "DisableOperationOptionCode"},
    {CiA402::HaltOptionCode, "HaltOptionCode"},
    {CiA402::FaultReactionOptionCode, "FaultReactionOptionCode"},
    {CiA402::ModesOfOperation, "ModesOfOperation"},
    {CiA402::ModesOfOperationDisplay, "ModesOfOperationDisplay"},
    {CiA402::PositionDemandValue, "PositionDemandValue"},
    {CiA402::PositionActualInternalValue, "PositionActualInternalValue"},
    {CiA402::PositionActualValue, "PositionActualValue"},
    {CiA402::FollowingErrorWindow, "FollowingErrorWindow"},
    {CiA402::FollowingErrorTimeout, "FollowingErrorTimeout"},
    {CiA402::PositionWindow, "PositionWindow"},
    {CiA402::PositionWindowTime, "PositionWindowTime"},
    {CiA402::VelocitySensorActualValue, "VelocitySensorActualValue"},
    {CiA402::SensorSelectionCode, "SensorSelectionCode"},
    {CiA402::VelocityDemandValue, "VelocityDemandValue"},
    {CiA402::VelocityActualValue, "VelocityActualValue"},
    {CiA402::VelocityWindow, "VelocityWindow"},
    {CiA402::VelocityWindowTime, "VelocityWindowTime"},
    {CiA402::VelocityThreshold, "VelocityThreshold"},
    {CiA402::VelocityThresholdTime, "VelocityThresholdTime"},
    {CiA402::TargetTorque, "TargetTorque"},
    {CiA402::MaxTorque, "MaxTorque"},
    {CiA402::MaxCurrent, "MaxCurrent"},
    {CiA402::TorqueDemandValue, "TorqueDemandValue"},
    {CiA402::MotorRatedCurrent, "MotorRatedCurrent"},
    {CiA402::MotorRatedTorque, "MotorRatedTorque"},
    {CiA402::TorqueActualValue, "TorqueActualValue"},
    {CiA402::CurrentActualValue, "CurrentActualValue"},
    {CiA402::DCLinkCircuitVoltage, "DCLinkCircuitVoltage"},
    {CiA402::TargetPosition, "TargetPosition"},
    {CiA402::PositionRangeLimit, "PositionRangeLimit"},
    {CiA402::HomeOffset, "HomeOffset"},
    {CiA402::SoftwarePositionLimit, "SoftwarePositionLimit"},
    {CiA402::Polarity, "Polarity"},
    {CiA402::MaxProfileVelocity, "MaxProfileVelocity"},
    {CiA402::MaxMotorSpeed, "MaxMotorSpeed"},
    {CiA402::ProfileVelocity, "ProfileVelocity"},
    {CiA402::EndVelocity, "EndVelocity"},
    {CiA402::ProfileAcceleration, "ProfileAcceleration"},
    {CiA402::ProfileDeceleration, "ProfileDeceleration"},
    {CiA402::QuickStopDeceleration, "QuickStopDeceleration"},
    {CiA402::MotionProfileType, "MotionProfileType"},
    {CiA402::TorqueSlope, "TorqueSlope"},
    {CiA402::TorqueProfileType, "TorqueProfileType"},
    {CiA402::PositionEncoderResolution, "PositionEncoderResolution"},
    {CiA402::VelocityEncoderResolution, "VelocityEncoderResolution"},
    {CiA402::GearRatio, "GearRatio"},
    {CiA402::FeedConstant, "FeedConstant"},
    {CiA402::VelocityFactor, "VelocityFactor"},
    {CiA402::AccelerationFactor, "AccelerationFactor"},
    {CiA402::HomingMethod, "HomingMethod"},
    {CiA402::HomingSpeeds, "HomingSpeeds"},
    {CiA402::HomingAcceleration, "HomingAcceleration"},
    {CiA402::JerkFactor, "JerkFactor"},
    {CiA402::ProfileJerkUse, "ProfileJerkUse"},
    {CiA402::ProfileJerk, "ProfileJerk"},
    {CiA402::SIUnitPosition, "SIUnitPosition"},
    {CiA402::SIUnitVelocity, "SIUnitVelocity"},
    {CiA402::SIUnitAcceleration, "SIUnitAcceleration"},
    {CiA402::SIUnitJerk, "SIUnitJerk"},
    {CiA402::PositionOffset, "PositionOffset"},
    {CiA402::VelocityOffset, "VelocityOffset"},
    {CiA402::TorqueOffset, "TorqueOffset"},
    {CiA402::AdditionalHomeOffset, "AdditionalHomeOffset"},
    {CiA402::TouchProbeFunction, "TouchProbeFunction"},
    {CiA402::TouchProbeStatus, "TouchProbeStatus"},
    {CiA402::TouchProbe1PositionPositiveEdge, "TouchProbe1PositionPositiveEdge"},
    {CiA402::TouchProbe1PositionNegativeEdge, "TouchProbe1PositionNegativeEdge"},
    {CiA402::TouchProbe2PositionPositiveEdge, "TouchProbe2PositionPositiveEdge"},
    {CiA402::TouchProbe2PositionNegativeEdge, "TouchProbe2PositionNegativeEdge"},
    {CiA402::InterpolationSubModeSelect, "InterpolationSubModeSelect"},
    {CiA402::InterpolationDataRecord, "InterpolationDataRecord"},
    {CiA402::InterpolationTimePeriod, "InterpolationTimePeriod"},
    {CiA402::InterpolationDataConfiguration, "InterpolationDataConfiguration"},
    {CiA402::MaxAcceleration, "MaxAcceleration"},
    {CiA402::MaxDeceleration, "MaxDeceleration"},
    {CiA402::LowVelocityLimitValue, "LowVelocityLimitValue"},
    {CiA402::HighVelocityLimitValue, "HighVelocityLimitValue"},
    {CiA402::TorqueLimitationOptionCode, "TorqueLimitationOptionCode"},
    {CiA402::AccelerationActualValue, "AccelerationActualValue"},
    {CiA402::TorqueLimitationStatus, "TorqueLimitationStatus"},
    {CiA402::TouchProbeSource, "TouchProbeSource"},
    {CiA402::TouchProbeTimeStamp1PositiveValue, "TouchProbeTimeStamp1PositiveValue"},
    {CiA402::TouchProbeTimeStamp1NegativeValue, "TouchProbeTimeStamp1NegativeValue"},
    {CiA402::TouchProbeTimeStamp2PositiveValue, "TouchProbeTimeStamp2PositiveValue"},
    {CiA402::TouchProbeTimeStamp2NegativeValue, "TouchProbeTimeStamp2NegativeValue"},
    {CiA402::TouchProbeTimeStamp1PositiveEdgeCounter, "TouchProbeTimeStamp1PositiveEdgeCounter"},
    {CiA402::TouchProbeTimeStamp1NegativeEdgeCounter, "TouchProbeTimeStamp1NegativeEdgeCounter"},
    {CiA402::TouchProbeTimeStamp2PositiveEdgeCounter, "TouchProbeTimeStamp2PositiveEdgeCounter"},
    {CiA402::TouchProbeTimeStamp2NegativeEdgeCounter, "TouchProbeTimeStamp2NegativeEdgeCounter"},
    {CiA402::PositiveTorqueLimitValue, "PositiveTorqueLimitValue"},
    {CiA402::NegativeTorqueLimitValue, "NegativeTorqueLimitValue"},
    {CiA402::SupportedHomingMethods, "SupportedHomingMethods"},
    {CiA402::AdditionalPositionActualValue, "AdditionalPositionActualValue"},
    {CiA402::AdditionalVelocityActualValue, "AdditionalVelocityActualValue"},
    {CiA402::AdditionalPositionEncoderResolutionEncoderIncrements, "AdditionalPositionEncoderResolutionEncoderIncrements"},  // NOLINT
    {CiA402::AdditionalVelocityEncoderResolutionEncoderIncPerSec, "AdditionalVelocityEncoderResolutionEncoderIncPerSec"},  // NOLINT
    {CiA402::AdditionalGearRatioMotorShaftRevolutions, "AdditionalGearRatioMotorShaftRevolutions"},  // NOLINT
    {CiA402::AdditionalFeedConstantFeed, "AdditionalFeedConstantFeed"},
    {CiA402::CommutationAngle, "CommutationAngle"},
    {CiA402::AdditionalPositionEncoderResolutionMotorRevolutions, "AdditionalPositionEncoderResolutionMotorRevolutions"},  // NOLINT
    {CiA402::AdditionalVelocityEncoderResolutionMotorRevPerSec, "AdditionalVelocityEncoderResolutionMotorRevPerSec"},  // NOLINT
    {CiA402::AdditionalGearRatioDrivingrShaftRevolutions, "AdditionalGearRatioDrivingrShaftRevolutions"},  // NOLINT
    {CiA402::AdditionalFeedDrivingrShaftRevolutions, "AdditionalFeedDrivingrShaftRevolutions"},
    {CiA402::AdditionalSensorSelection, "AdditionalSensorSelection"},
    {CiA402::EncoderInversion, "EncoderInversion"},
    {CiA402::AdditionalEncoderInversion, "AdditionalEncoderInversion"},
    {CiA402::PositioningOptionCode, "PositioningOptionCode"},
    {CiA402::FollowingErrorActualValue, "FollowingErrorActualValue"},
    {CiA402::MaxSlippage, "MaxSlippage"},
    {CiA402::ControlEffort, "ControlEffort"},
    {CiA402::PositionDemandInternalValue, "PositionDemandInternalValue"},
    {CiA402::DigitalInputs, "DigitalInputs"},
    {CiA402::DigitalOutputs, "DigitalOutputs"},
    {CiA402::TargetVelocity, "TargetVelocity"},
    {CiA402::PositionActualValue64Bit, "PositionActualValue64Bit"},
    {CiA402::AdditionalPositionActualValue64Bit, "AdditionalPositionActualValue64Bit"},
    {CiA402::CAMStateRegister, "CAMStateRegister"},
    {CiA402::CAMEnableRegister, "CAMEnableRegister"},
    {CiA402::CAMPolarityRegister, "CAMPolarityRegister"},
    {CiA402::CAMPositionSelectionRegister, "CAMPositionSelectionRegister"},
    {CiA402::CAM1LowLimit, "CAM1LowLimit"},
    {CiA402::CAM2LowLimit, "CAM2LowLimit"},
    {CiA402::CAM3LowLimit, "CAM3LowLimit"},
    {CiA402::CAM4LowLimit, "CAM4LowLimit"},
    {CiA402::CAM1HighLimit, "CAM1HighLimit"},
    {CiA402::CAM2HighLimit, "CAM2HighLimit"},
    {CiA402::CAM3HighLimit, "CAM3HighLimit"},
    {CiA402::CAM4HighLimit, "CAM4HighLimit"},
    {CiA402::CAM1Hysteresis, "CAM1Hysteresis"},
    {CiA402::CAM2Hysteresis, "CAM2Hysteresis"},
    {CiA402::CAM3Hysteresis, "CAM3Hysteresis"},
    {CiA402::CAM4Hysteresis, "CAM4Hysteresis"},
    {CiA402::CAM1PositionSourceSelection, "CAM1PositionSourceSelection"},
    {CiA402::CAM2PositionSourceSelection, "CAM2PositionSourceSelection"},
    {CiA402::CAM3PositionSourceSelection, "CAM3PositionSourceSelection"},
    {CiA402::CAM4PositionSourceSelection, "CAM4PositionSourceSelection"},
    {CiA402::CAM1Duration, "CAM1Duration"},
    {CiA402::CAM2Duration, "CAM2Duration"},
    {CiA402::CAM3Duration, "CAM3Duration"},
    {CiA402::CAM4Duration, "CAM4Duration"},
    {CiA402::CAM1SwitchPointConfiguration, "CAM1SwitchPointConfiguration"},
    {CiA402::CAM2SwitchPointConfiguration, "CAM2SwitchPointConfiguration"},
    {CiA402::CAM3SwitchPointConfiguration, "CAM3SwitchPointConfiguration"},
    {CiA402::CAM4SwitchPointConfiguration, "CAM4SwitchPointConfiguration"},
    {CiA402::MotorType, "MotorType"},
    {CiA402::MotorCatalogueNumber, "MotorCatalogueNumber"},
    {CiA402::MotorManufacturer, "MotorManufacturer"},
    {CiA402::HttpMotorCatalogueAddress, "HttpMotorCatalogueAddress"},
    {CiA402::MotorCalibrationDate, "MotorCalibrationDate"},
    {CiA402::MotorServicePeriod, "MotorServicePeriod"},
    {CiA402::SupportedDriveModes, "SupportedDriveModes"},
    {CiA402::DriveCatalogueNumber, "DriveCatalogueNumber"},
    {CiA402::HttpDriveCatalogueAddress, "HttpDriveCatalogueAddress"},
    {CiA402::VersionNumber, "VersionNumber"}
};

}  // namespace crf::devices::canopendrivers
