#!/bin/bash

pathToFile=${1:1:-1}
pathToFile+="/bin/testfiles/"

# Download process
cd $pathToFile
wget -nc https://cernbox.cern.ch/remote.php/dav/public-files/CW2Z6HlMulJRLuK/testOrganizedCloud.pcd?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjY2NzA4OTUxLCJpYXQiOjE2NjY2MjI1NTEsImlzcyI6Imh0dHBzOi8vYXV0aC5jZXJuLmNoL2F1dGgvcmVhbG1zL2Nlcm4iLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vYXV0aC5jZXJuLmNoL2F1dGgvcmVhbG1zL2Nlcm4iLCJvcGFxdWVfaWQiOiJqcGxheWFuZyIsInR5cGUiOjF9LCJ1c2VybmFtZSI6ImpwbGF5YW5nIiwibWFpbCI6ImpvcmdlLnBsYXlhbi5nYXJhaUBjZXJuLmNoIiwiZGlzcGxheV9uYW1lIjoiSm9yZ2UgUGxheWFuIEdhcmFpIiwidWlkX251bWJlciI6MTM1MjczLCJnaWRfbnVtYmVyIjoyNzY2fSwic2NvcGUiOnsidXNlciI6eyJyZXNvdXJjZSI6eyJkZWNvZGVyIjoianNvbiIsInZhbHVlIjoiZXlKd1lYUm9Jam9pTHlKOSJ9LCJyb2xlIjoxfX19.CWY5j7eksT5LGCpMrSYLLOSnPCjTgXRYK28_fIKWaQs -O OrganizedPointCloud.pcd
wget -nc https://cernbox.cern.ch/remote.php/dav/public-files/WSQ7fHVU3gFLqz7/testUnOrganizedCloud.pcd?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNjY2NzA4OTUxLCJpYXQiOjE2NjY2MjI1NTEsImlzcyI6Imh0dHBzOi8vYXV0aC5jZXJuLmNoL2F1dGgvcmVhbG1zL2Nlcm4iLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vYXV0aC5jZXJuLmNoL2F1dGgvcmVhbG1zL2Nlcm4iLCJvcGFxdWVfaWQiOiJqcGxheWFuZyIsInR5cGUiOjF9LCJ1c2VybmFtZSI6ImpwbGF5YW5nIiwibWFpbCI6ImpvcmdlLnBsYXlhbi5nYXJhaUBjZXJuLmNoIiwiZGlzcGxheV9uYW1lIjoiSm9yZ2UgUGxheWFuIEdhcmFpIiwidWlkX251bWJlciI6MTM1MjczLCJnaWRfbnVtYmVyIjoyNzY2fSwic2NvcGUiOnsidXNlciI6eyJyZXNvdXJjZSI6eyJkZWNvZGVyIjoianNvbiIsInZhbHVlIjoiZXlKd1lYUm9Jam9pTHlKOSJ9LCJyb2xlIjoxfX19.CWY5j7eksT5LGCpMrSYLLOSnPCjTgXRYK28_fIKWaQs -O UnorganizedPointCloud.pcd
