#######################################################################################################################
##                                                                                                                   ##
## © Copyright CERN 2023. All rights reserved. This software is released under a CERN proprietary software license.  ##
## Any permission to use it shall be granted in writing. Requests shall be addressed to CERN through mail-KT@cern.ch ##
##                                                                                                                   ##
## Author: Jorge Playan Garai CERN BE/CEM/MRO 2023                                                                   ##
##                                                                                                                   ##
#######################################################################################################################

master:
    node_id: 1
    sync_period: 50000  # us
    heartbeat_producer: 10  # ms

.MaxonEPOS4_motor: &motor
    dcf: "MaxonEPOS4.eds"
    dcf_path: "cpproboticframework/modules/Actuators/Robot/config/CiA402Robot/CERNBotC1"
    heartbeat_producer: 10  # ms

    rpdo:
        1:
            enabled: true
            cob_id: auto
            transmission: 0x01
            mapping:
                - {index: 0x607A, sub_index: 0x00} # target position
                - {index: 0x60FF, sub_index: 0x00} # target velocity
        2:
            enabled: true
            cob_id: auto
            transmission: 0x01
            mapping:
            # value with 6 bytes
                - {index: 0x6071,  sub_index: 0x00} # target torque

    tpdo:
        1:
            enabled: true
            cob_id: auto
            transmission: 0x01  # SYNC
            mapping:
                - {index: 0x6041, sub_index: 0x00}  # status word
                - {index: 0x6064, sub_index: 0x00}  # actual position value register
        2:
            enabled: true
            cob_id: auto
            transmission: 0x01  # SYNC
            mapping:
                - {index: 0x6061,  sub_index: 0x00} # mode of operation display
                - {index: 0x606C,  sub_index: 0x00} # actual velocity value register
        3:
            enabled: true
            cob_id: auto
            transmission: 0x01  # SYNC
            mapping:
                - {index: 0x6077,  sub_index: 0x00} # actual torque value register

slave_joint1:
    node_id: 3
    <<: *motor

slave_joint2:
    node_id: 4
    <<: *motor

slave_joint3:
    node_id: 5
    <<: *motor

slave_joint4:
    node_id: 6
    <<: *motor
